#!/bin/bash

DOUBAN_HOST="pypi.doubanio.com"
DOUBAN_URL="http://pypi.doubanio.com/simple/"

TSINGHUA_HOST="pypi.tuna.tsinghua.edu.cn"
TSINGHUA_URL="https://pypi.tuna.tsinghua.edu.cn/simple/"

ALIYUN_HOST="mirrors.aliyun.com"
ALIYUN_URL="https://mirrors.aliyun.com/pypi/simple/"




TRUSTED_HOST="pypi.doubanio.com"
INDEX_URL="http://pypi.doubanio.com/simple/"

function install_sys_pkg()
{
		# make sure python3 virtual env is installed
		echo "Check if python3-venv is installed..."
		pkg='python3-venv'
		if [ `dpkg -l | grep $pkg | wc -l` -ne 0 ]; then
				echo "[ INSTALLED ]"
		else
				echo "[ NOT INSTALLED ]"
				sudo apt install python3-venv
		fi
}


function clean()
{
    # clean up existing virtual env
    set -x
    rm activate
    rm -rf environ
    set +x
    echo "Clean up virtual env, Done!"
}

function boot()
{
		# check and install python virtual env
		install_sys_pkg
    # create virtual env and install python pakage
    if [ ! -d "environ" ]; then
        # using python3 built-in venv module
        python3 -m venv ./environ
    fi

    ln -sf environ/bin/activate
    . ./activate

    pip install --upgrade -i $INDEX_URL --trusted-host $TRUSTED_HOST -r requirements.pip \
        || die "Could not install python packages ! Cannot continue"

    # upgrade pip
    #pip install --upgrade -i $INDEX_URL pip

    # Install wheel
    #pip install --upgrade -i $INDEX_URL  wheel \
    #    || die "Could not install wheel ! Cannot continue"

    #pip install --upgrade -i $INDEX_URL --trusted-host -r requirements.pip \
    #    || die "Could not install python packages ! Cannot continue"
}

show_usage() {
    echo "Invalid arguments"
    echo "Usage: $0 [--clean] / [None]"
    exit 1
}

if (( ! "$#" ));then
    boot
else
     case "$1" in
        --clean)
            clean
            ;;
        --help)
            show_usage
            ;;
        *)
            show_usage
            ;;
    esac
fi
